# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Gabriel Hagui dos Santos - Software Engineer & DevOps
# email: example@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Engenharia de Software sem ruído. Cloud AWS, Serverless, automação e arquitetura limpa.
  Documentação técnica, projetos open source e experimentos com design neubrutalist.
baseurl: "/Gabriel_Hagui" # Required for GitHub Pages
url: "https://ghagui.github.io" # the base hostname & protocol for your site
# twitter_username: ghagui
github_username: GHagui
linkedin_username: gabriel-hagui

# Author information
author:
  name: Gabriel Hagui dos Santos
#  email: example@example.com
#  twitter: ghagui

# SEO Settings
lang: pt-BR
timezone: America/Sao_Paulo

# Social media
social:
  name: Gabriel Hagui dos Santos
  links:
    - https://github.com/GHagui
    - https://www.linkedin.com/in/gabriel-hagui
    - https://t.me/g_hagui

# Logo and images
logo: /assets/images/gabriel-hagui.webp
social_image_path: /assets/images/gabriel-hagui.webp

# Twitter Card settings
twitter:
#  username: ghagui
  card: summary_large_image

# Facebook/Open Graph settings
#facebook:
#  app_id:
#  publisher:
#  admins:

# Webmaster verification (uncomment and add your codes when ready)
# webmaster_verifications:
#   google:
#   bing:
#   alexa:
#   yandex:
#   baidu:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-sitemap  # Using custom sitemap.xml instead

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  math_engine: mathjax
  math_engine_opts:
    # Allow both $...$ and \(...\) for inline, and $$...$$ / \[...\] for display
    preview: "TeX"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
